### ISSUE TITLE
Seeing permission denied when attempting to run docker image

### ISSUE THREAD

**Issue by BeatLink** [saierd/docker-etesync#1]
Command ran:
`docker run --name=etesync --restart always -v /opt/etesync:/data -p 8080:3735 dsaier/etesync`

Output
```
Traceback (most recent call last):
  File "/opt/etesync/etesync_server/utils.py", line 19, in get_secret_from_file
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/secret.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/etesync/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/etesync/etesync_server/settings.py", line 185, in <module>
    SECRET_KEY = get_secret_from_file(SECRET_FILE)
  File "/opt/etesync/etesync_server/utils.py", line 22, in get_secret_from_file
    with open(path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/data/secret.txt'

```

**Comment by BeatLink** [comment]
This could be solved by creating the secret.txt file if it doesnt exist

**Comment by BeatLink** [comment]
Turns out it was a permissions issue on my end. This can be closed
